export class Student {
  constructor(
    public readonly id: string,
    public name: string,
    public socialName: string | null,
    public cpf: string,
    public birthDate: Date,
    public phone: string,
    public email: string,
    public password: string,
    public gender: string,
    public race: string,
    public cep: string | null,
    public address: string | null,
    public complement: string | null,
    public neighborhood: string | null,
    public city: string | null,
    public state: string | null,
    public education: string,
    public courseName: string | null,
    public institution: string | null,
    public fatilabMotivation: string,
    public howHeard: string | null,
    public hasComputer: boolean | null,
    public hasInternet: boolean | null,
    public committedToParticipate: boolean | null,
    public familyIncome: string | null,
    public householdSize: number | null,
    public socialBenefits: string | null,
    public hasProgrammingExperience: boolean | null,
    public hasTechCourses: boolean | null,
    public techCoursesList: string | null,
    public isEmployed: boolean | null,
    public workArea: string | null,
    public isPcd: boolean,
    public disabilityType: string | null,
    public disabilityDescription: string | null,
    public hasMedicalReport: string | null,
    public accessibilityResources: string | null,
    public specificAccessibilityNeeds: string | null,
    public authorizesImageUse: boolean,
    public acceptsLgpd: boolean,
    public sendCurriculum: boolean,
    public createdAt: Date,
    public updatedAt: Date,
  ) {}
}